# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import necestovka.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Aerolinky',
            },
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Letiště',
            },
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Volitelné služby',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('arrive_time', models.DateTimeField()),
                ('airlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_fly_airlines', to='necestovka.Airlines')),
                ('arrive_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_arrive_airport', to='necestovka.Airports')),
            ],
            options={
                'verbose_name_plural': 'Lety',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.CharField(default=necestovka.models.auto_id, max_length=8, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('final_price', models.IntegerField(blank=True, null=True)),
                ('passangers_count', models.IntegerField(blank=True, null=True)),
                ('checked_luggage', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('paid', 'Zaplacena'), ('in_progress', 'Rozpracovana'), ('new', 'Nova'), ('canceled', 'Zrusena')], max_length=50)),
                ('bank_name', models.CharField(blank=True, choices=[('CSOB', 'CSOB'), ('Unicredit', 'Unicredit'), ('KB', 'KB')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Objednávky',
            },
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('born_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('luggage_hand', models.CharField(blank=True, max_length=25, null=True)),
                ('luggage_cabin', models.CharField(blank=True, max_length=25, null=True)),
                ('luggage_checked', models.CharField(blank=True, max_length=25, null=True)),
                ('orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_passengers_orders', to='necestovka.Orders')),
            ],
            options={
                'verbose_name_plural': 'Pasažéři',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_ref', models.CharField(max_length=15)),
                ('booking_status', models.CharField(default='', max_length=50)),
                ('fly_number', models.CharField(blank=True, max_length=30)),
                ('depart_time', models.DateTimeField()),
                ('arrive_time', models.DateTimeField()),
                ('terminal', models.CharField(blank=True, max_length=15)),
                ('baggage_allowed', models.CharField(blank=True, max_length=200)),
                ('airlines', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ticket_airlines', to='necestovka.Airlines')),
                ('arrive_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ticket_arrive_airport', to='necestovka.Airports')),
                ('depart_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ticket_depart_airport', to='necestovka.Airports')),
                ('orders', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ticket_orders', to='necestovka.Orders')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ticket_passenger', to='necestovka.Passengers')),
            ],
            options={
                'verbose_name_plural': 'Letenky',
            },
        ),
        migrations.AddField(
            model_name='passengers',
            name='tickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_passengers_tickets', to='necestovka.Tickets'),
        ),
        migrations.AddField(
            model_name='orders',
            name='contact_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_orders_passenger_primary', to='necestovka.Passengers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='extras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_orders_extras', to='necestovka.Extras'),
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_flights',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_orders_ordered_flights', to='necestovka.Flights'),
        ),
        migrations.AddField(
            model_name='orders',
            name='passengers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_orders_passengers', to='necestovka.Passengers'),
        ),
        migrations.AddField(
            model_name='flights',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_fly_orders', to='necestovka.Orders'),
        ),
        migrations.AddField(
            model_name='flights',
            name='start_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_start_airport', to='necestovka.Airports'),
        ),
    ]
